name: nodes
description: An application for The Grid Management Company.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  expandable_section: ^0.0.3
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bot_toast: ^4.1.3
  logging: ^1.2.0
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  jiffy: ^6.2.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  permission_handler: ^11.0.1
  flutter_form_builder: ^6.1.0+1
  flutter_toggle_tab: ^1.4.1
  enum_to_string: ^2.0.1
  pinput: ^3.0.1
  flutter_svg: ^2.0.9

  regexed_validator: ^2.0.0+1
  camera: ^0.10.5+5
  flutter_multi_formatter: ^2.11.16
  # firebase_core: ^2.20.0
  # firebase_messaging: ^14.7.2
  # firebase_crashlytics: ^3.4.6
  flutter_local_notifications: ^9.9.1
  upgrader: ^8.2.0
  material_design_icons_flutter: ^7.0.7296
  uuid: ^4.2.1
  flutter_dialogs: ^3.0.0
  datepicker_dropdown: ^0.0.7+5
  multiple_search_selection: ^2.6.1
  flutter_textfield_autocomplete: ^1.0.2
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.2
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  device_preview: ^1.1.0
  sticky_headers: "^0.3.0"
  flutter_countdown_timer: ^4.1.0
  flutter_paystack_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.9.2

dependency_overrides:
  # // These overrides are for recent paystack to work...
  intl: ^0.17.0 

flutter_native_splash:
  image: assets/images/png/splash.png
  color: "#085A55"
  image_dark: assets/images/png/splash.png
  android: true
  ios: true

flutter_icons:
  android: "nodes_icon"
  ios: true
  image_path: "assets/images/png/launcher_icon.png"
  adaptive_icon_background: "#085A55"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/generalSans/
    - assets/fonts/

  fonts:

    - family: generalSans
      fonts:
        - asset: assets/fonts/generalSans/GeneralSans_Bold.otf
          weight: 800
        - asset: assets/fonts/generalSans/GeneralSans_SemiBold.otf
          weight: 700
        - asset: assets/fonts/generalSans/GeneralSans_Medium.otf
          weight: 600
        - asset: assets/fonts/generalSans/GeneralSans_Regular.otf
          weight: 500
        - asset: assets/fonts/generalSans/GeneralSans_Light.otf
          weight: 400
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
